### ISSUE TITLE
Automated ingest of license seems broken

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckanext-snap_harvester#11]
When we ingest, data sets that do have a license _do_ get the core field populated correctly but there's an empty item in the `pkg_extras` dict that I think breaks the editor in CKAN, if you try and edit a record with a license attached it barfs on the validation of the license and you can't delete that key.  Not sure what's up with that.  [Possibly the same issue here](https://github.com/ckan/ckan/issues/2110).

**Comment by brucecrevensten** [comment]
There is some odd issue going on and the fix suggested on that other ticket just didn't work for me.  I'm going to just patch CKAN core to remove the problematic checks.  In file `/usr/lib/ckan/default/src/ckan/ckan/model/license.py` I changed line 32 to simply `return False`.

**Comment by brucecrevensten** [comment]
Decided to hardcode the license in our ingest -- it'll work for everything we've got for now at least.

**Comment by brucecrevensten** [comment]
We actually want to fix this properly because otherwise (1) we have a hack fix in place and (2) we can't properly use licenses in items created outside of the harvest.

**Comment by takurkowski** [comment]
in case this matters

https://github.com/ua-snap/ckanext-snap_theme/issues/4

**Comment by brucecrevensten** [comment]
Current state of things: ingesting the license does break and we don't have an immediately-good option -- we can suck in the URL to the license, but that's not exactly awesome.  Instead, Tom's elected to leave things as-is for now because it works for our current assets.  When we need to address the license issue, we'll open a ticket and deal with it.
