### ISSUE TITLE
Don't assign license as part of the ingest process

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckanext-snap_harvester#23]
Instead, we need to take the license specified in GeoNetwork and make sure it's ingested properly.

**Comment by takurkowski** [comment]
this also displays on the resource page, for instance, if I attached a URL to a published article, it lists a license, which is not correct.

**Comment by takurkowski** [comment]
this lives in geonetwork under:
Point of Contact: other constraints : http://creativecommons.org/licenses/by-nc-sa/3.0/

**Comment by takurkowski** [comment]
Is the title of this one an issue still? I don't think the harvester is reading any license info from GeoN, which is fine given we can display the license directly once we implement:

https://github.com/ua-snap/ckanext-snap_theme/issues/4

**Comment by brucecrevensten** [comment]
Current state of things: ingesting the license does break and we don't have an immediately-good option -- we can suck in the URL to the license, but that's not exactly awesome.  Instead, Tom's elected to leave things as-is for now because it works for our current assets.  When we need to address the license issue, we'll open a ticket and deal with it.
