### ISSUE TITLE
Update license on ingest

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckanext-snap_harvester#32]
Should be, for all data records ingested from our GN instance:

Creative Commons Attribution 4.0 International License
http://creativecommons.org/licenses/by/4.0/

**Comment by takurkowski** [comment]
Can you implement this by Tues? I have some data to have a collaborator review, and would like to have this fixed before then.

**Comment by takurkowski** [comment]
correct text and url:

Creative Commons Attribution 4.0 International License
http://creativecommons.org/licenses/by/4.0/
